"""Access layer codegen from ``policies/access.yml`` (design decisions F4, F5).

One dbt model per role and table, materialized as a TABLE, carrying only what the role may
see: rows of its own product(s), sensitive columns dropped, direct personal data masked. A
generated ``policies/gateway_allowlist.json`` lists the tables and columns each role may read
through the gateway. The text is produced as ``{path: content}`` so ``generate`` and ``check``
share one code path (CI fails when the committed files differ).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

import yaml

from .metrics.codegen import generated_columns, generated_descriptions
from .metrics.spec import MetricsSpec
from .scan import MASKS, PII_CLASSES

HEADER: Final = "GENERATED by `platform access generate` from policies/access.yml - do not edit."
ACCESS_DIR: Final = "dbt/models/access"
ALLOWLIST_PATH: Final = "policies/gateway_allowlist.json"
YML_PATH: Final = f"{ACCESS_DIR}/_access.yml"

#: mask kind -> (macro, suffix of the masked output column)
MASK_RULES: Final = {
    "email_domain": ("mask_email_domain", "domain"),
    "phone_last4": ("mask_phone_last4", "last4"),
    "birth_year": ("mask_birth_year", "year"),
    "initial": ("mask_initial", "initial"),
}


class PolicyError(ValueError):
    """policies/access.yml is malformed or inconsistent with the dbt declarations."""


@dataclass(frozen=True)
class Role:
    """One role of the policy."""

    name: str
    description: str
    products: tuple[str, ...] | None  # None = all products
    sensitive: str
    direct: str


@dataclass(frozen=True)
class RowScope:
    """How a product role is restricted to its own rows."""

    kind: str
    columns: dict[str, str]
    column: str = ""
    product: str = ""


@dataclass(frozen=True)
class TableRule:
    """A base table exposed through the access layer."""

    name: str
    layer: str
    scope: RowScope


@dataclass(frozen=True)
class Policy:
    """The parsed policy."""

    roles: tuple[Role, ...]
    tables: tuple[TableRule, ...]
    metric_scope: RowScope | None


@dataclass(frozen=True)
class ColumnInfo:
    """A base column with its declared class (and mask when direct)."""

    name: str
    pii: str
    mask: str | None = None
    description: str = ""


def _scope(raw: dict[str, Any], where: str) -> RowScope:
    kind = str(raw.get("kind", ""))
    if kind not in {"none", "flags", "column", "fixed"}:
        raise PolicyError(f"{where}: unknown row_scope kind {kind!r}")
    scope = RowScope(
        kind=kind,
        columns={str(k): str(v) for k, v in (raw.get("columns") or {}).items()},
        column=str(raw.get("column", "")),
        product=str(raw.get("product", "")),
    )
    missing = (
        (kind == "flags" and not scope.columns)
        or (kind == "column" and not scope.column)
        or (kind == "fixed" and not scope.product)
    )
    if missing:
        raise PolicyError(f"{where}: row_scope {kind} is missing its parameters")
    return scope


def parse_policy(raw: dict[str, Any]) -> Policy:
    """Validate a parsed YAML document."""
    if raw.get("version") != 1:
        raise PolicyError("access.yml: version must be 1")
    roles: list[Role] = []
    for name, item in (raw.get("roles") or {}).items():
        products = item.get("products")
        if products != "all" and not (isinstance(products, list) and products):
            raise PolicyError(f"role {name}: products must be 'all' or a list")
        if item.get("sensitive") not in {"exclude", "include"}:
            raise PolicyError(f"role {name}: sensitive must be exclude or include")
        if item.get("direct") not in {"mask", "clear"}:
            raise PolicyError(f"role {name}: direct must be mask or clear")
        roles.append(
            Role(
                name=str(name),
                description=str(item.get("description", "")),
                products=None if products == "all" else tuple(str(p) for p in products),
                sensitive=str(item["sensitive"]),
                direct=str(item["direct"]),
            )
        )
    if not roles:
        raise PolicyError("access.yml defines no roles")
    tables = tuple(
        TableRule(str(t["name"]), str(t["layer"]), _scope(t.get("row_scope") or {}, str(t["name"])))
        for t in raw.get("tables", [])
    )
    generated = raw.get("generated_metrics")
    metric_scope = _scope(generated["row_scope"], "generated_metrics") if generated else None
    return Policy(tuple(roles), tables, metric_scope)


def load_policy(path: Path) -> Policy:
    """Read and validate ``path``."""
    return parse_policy(yaml.safe_load(path.read_text(encoding="utf-8")))


def _yml_columns(path: Path, key: str) -> dict[str, list[ColumnInfo]]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    out: dict[str, list[ColumnInfo]] = {}
    for model in raw.get(key, []):
        columns: list[ColumnInfo] = []
        for column in model.get("columns", []):
            meta = (column.get("config") or {}).get("meta") or {}
            pii = meta.get("pii")
            if pii not in PII_CLASSES:
                raise PolicyError(f"{model['name']}.{column['name']}: missing or invalid meta.pii")
            mask = meta.get("mask")
            if pii == "direct" and mask not in MASKS:
                raise PolicyError(f"{model['name']}.{column['name']}: direct needs a valid mask")
            columns.append(
                ColumnInfo(str(column["name"]), str(pii), mask, str(column.get("description", "")))
            )
        out[str(model["name"])] = columns
    return out


def load_columns(repo_root: Path, spec: MetricsSpec) -> dict[str, list[ColumnInfo]]:
    """Declared columns of every silver / gold table and of the generated metric models."""
    columns: dict[str, list[ColumnInfo]] = {}
    columns.update(_yml_columns(repo_root / "dbt/models/silver/_models.yml", "models"))
    columns.update(_yml_columns(repo_root / "dbt/models/gold/_models.yml", "models"))
    columns.update(_yml_columns(repo_root / "dbt/seeds/_seeds.yml", "seeds"))
    described = generated_descriptions(spec)
    for model, cols in generated_columns(spec).items():
        columns[model] = [
            ColumnInfo(name, "none", None, described[model][name]) for name, _ in cols
        ]
    return columns


def model_name(role: Role, table: str) -> str:
    """dbt model name of a role's copy of a table."""
    return f"acc_{role.name}__{table}"


def _row_filter(role: Role, scope: RowScope) -> tuple[bool, str]:
    """``(granted, where clause)`` for ``role`` and a table scope."""
    if scope.kind == "none" or role.products is None:
        return True, ""
    if scope.kind == "fixed":
        return scope.product in role.products, ""
    if scope.kind == "column":
        values = ", ".join(f"'{p}'" for p in role.products)
        op = f"= {values}" if len(role.products) == 1 else f"in ({values})"
        return True, f"where {scope.column} {op}"
    flags = [scope.columns[p] for p in role.products if p in scope.columns]
    if not flags:
        return False, ""
    return True, "where " + " or ".join(flags)


def _visible(role: Role, columns: list[ColumnInfo]) -> list[tuple[ColumnInfo, str, str]]:
    """``(column, output name, expression)`` for what ``role`` sees of a table."""
    out: list[tuple[ColumnInfo, str, str]] = []
    for c in columns:
        if c.pii == "sensitive" and role.sensitive == "exclude":
            continue
        if c.pii == "direct" and role.direct == "mask":
            assert c.mask is not None
            macro, suffix = MASK_RULES[c.mask]
            out.append((c, f"{c.name}_{suffix}", f"{{{{ {macro}('{c.name}') }}}}"))
        else:
            out.append((c, c.name, c.name))
    return out


def _sql(role: Role, table: str, columns: list[ColumnInfo], where: str) -> str:
    items = []
    for _, name, expr in _visible(role, columns):
        items.append(f"    {expr}" if expr == name else f"    {expr} as {name}")
    body = "select\n" + ",\n".join(items) + f"\nfrom {{{{ ref('{table}') }}}}"
    if where:
        body += f"\n{where}"
    return f"-- {HEADER}\n{body}\n"


MASK_TEXT: Final = {
    "email_domain": "only the domain part",
    "phone_last4": "only the last four digits",
    "birth_year": "only the year",
    "initial": "only the first character",
}


def _out_description(column: ColumnInfo, role: Role) -> str:
    if column.pii == "direct" and role.direct == "mask":
        assert column.mask is not None
        return (
            f"Masked: {MASK_TEXT[column.mask]} of the original column. {column.description}".strip()
        )
    return column.description


def _out_class(column: ColumnInfo, role: Role) -> str:
    if column.pii == "direct" and role.direct == "mask":
        return "quasi"
    return column.pii


def _yaml_str(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _exposed(policy: Policy, columns: dict[str, list[ColumnInfo]]) -> list[tuple[str, RowScope]]:
    tables = [(t.name, t.scope) for t in policy.tables]
    if policy.metric_scope is not None:
        for name in sorted(columns):
            if name.startswith(("metric_", "recon_")):
                tables.append((name, policy.metric_scope))
    for name, _ in tables:
        if name not in columns:
            raise PolicyError(f"table {name!r} has no declared columns in the dbt yml files")
    return tables


def generate_access_files(policy: Policy, columns: dict[str, list[ColumnInfo]]) -> dict[str, str]:
    """Every generated file as ``{repo-relative path: content}``."""
    files: dict[str, str] = {}
    model_entries: list[str] = []
    sensitive = sorted({c.name for cols in columns.values() for c in cols if c.pii == "sensitive"})
    allowlist: dict[str, Any] = {
        "generated": HEADER,
        # names of columns declared sensitive anywhere: the gateway audit flags a query that
        # merely mentions one, even when the role cannot read it
        "sensitive_columns": sensitive,
        "roles": {},
    }
    exposed = _exposed(policy, columns)
    for role in policy.roles:
        granted: dict[str, Any] = {}
        for table, scope in exposed:
            ok, where = _row_filter(role, scope)
            if not ok:
                continue
            cols = columns[table]
            files[f"{ACCESS_DIR}/{model_name(role, table)}.sql"] = _sql(role, table, cols, where)
            visible = _visible(role, cols)
            granted[table] = {
                "model": model_name(role, table),
                "columns": [name for _, name, _ in visible],
                "pii": {name: _out_class(c, role) for c, name, _ in visible},
                "descriptions": {name: _out_description(c, role) for c, name, _ in visible},
            }
            entries = "".join(
                f"      - name: {name}\n        description: "
                f"{_yaml_str(_out_description(c, role))}\n        config:\n          meta:\n"
                f"            pii: {_out_class(c, role)}\n"
                for c, name, _ in visible
            )
            model_entries.append(
                f"  - name: {model_name(role, table)}\n"
                f"    description: {_yaml_str(f'Role {role.name}: access copy of {table}.')}\n"
                f"    columns:\n{entries}"
            )
        allowlist["roles"][role.name] = {
            "description": role.description,
            "products": "all" if role.products is None else list(role.products),
            "sensitive_columns": role.sensitive,
            "direct_columns": role.direct,
            "tables": granted,
        }
    files[YML_PATH] = f"# {HEADER}\nversion: 2\n\nmodels:\n" + "".join(model_entries)
    files[ALLOWLIST_PATH] = json.dumps(allowlist, indent=2, ensure_ascii=False) + "\n"
    return files


def _existing(repo_root: Path) -> list[str]:
    directory = repo_root / ACCESS_DIR
    if not directory.is_dir():
        return []
    return [f"{ACCESS_DIR}/{p.name}" for p in sorted(directory.iterdir()) if p.is_file()]


def write_access_files(files: dict[str, str], repo_root: Path) -> None:
    """Write generated files and delete stale generated access models."""
    for rel, content in files.items():
        target = repo_root / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    for rel in _existing(repo_root):
        if rel not in files:
            (repo_root / rel).unlink()


def check_access_files(files: dict[str, str], repo_root: Path) -> list[str]:
    """Regenerate and compare: the access layer and the allowlist must be up to date."""
    problems: list[str] = []
    for rel, expected in files.items():
        path = repo_root / rel
        if not path.exists():
            problems.append(f"generated file is missing: {rel} (run `platform access generate`)")
        elif path.read_text(encoding="utf-8") != expected:
            problems.append(f"generated file is out of date or was edited: {rel}")
    problems += [
        f"stale generated file not in the policy: {rel}"
        for rel in _existing(repo_root)
        if rel not in files
    ]
    return problems


def check_access_manifest(policy: Policy, manifest: dict[str, Any]) -> list[str]:
    """No column declared ``sensitive`` (or unmasked ``direct``) in a restricted role's models."""
    problems: list[str] = []
    restricted = {r.name: r for r in policy.roles if r.sensitive == "exclude"}
    for node in manifest.get("nodes", {}).values():
        if node.get("resource_type") != "model" or node.get("schema") != "access":
            continue
        name = str(node.get("name", ""))
        role = next((r for r in restricted.values() if name.startswith(f"acc_{r.name}__")), None)
        if role is None:
            continue
        for column, entry in node.get("columns", {}).items():
            meta = (entry.get("config") or {}).get("meta") or entry.get("meta") or {}
            if meta.get("pii") in {"sensitive", "direct"}:
                problems.append(f"{name}.{column} is {meta.get('pii')} in a restricted role")
    return problems


__all__ = [
    "ColumnInfo",
    "Policy",
    "PolicyError",
    "check_access_files",
    "check_access_manifest",
    "generate_access_files",
    "load_columns",
    "load_policy",
    "parse_policy",
    "write_access_files",
]
