-- GENERATED by `platform metrics generate` from metrics/metrics.yml - do not edit.
with variants as (

    select
        'A' as product,
        'iap_revenue' as reported_as,
        'any' as expected_direction,
        0.0 as direction_tolerance_pct,
        2.0 as threshold_pct,
        true as comparable

    union all

    select
        'B' as product,
        'booking_revenue' as reported_as,
        'any' as expected_direction,
        0.0 as direction_tolerance_pct,
        0.0 as threshold_pct,
        false as comparable

    union all

    select
        'C' as product,
        'monthly_revenue' as reported_as,
        'any' as expected_direction,
        0.0 as direction_tolerance_pct,
        0.0 as threshold_pct,
        false as comparable

    union all

    select
        'D' as product,
        'net_sales' as reported_as,
        'lower' as expected_direction,
        0.0 as direction_tolerance_pct,
        15.0 as threshold_pct,
        true as comparable

    union all

    select
        'E' as product,
        'mrr' as reported_as,
        'any' as expected_direction,
        0.0 as direction_tolerance_pct,
        0.0 as threshold_pct,
        false as comparable

),

joined as (

    select
        k.period_month,
        k.product,
        k.reported_as,
        k.value as reported_value,
        c.net_revenue as canonical_value,
        v.expected_direction,
        v.direction_tolerance_pct,
        v.threshold_pct,
        v.comparable
    from {{ ref('brz_reported_kpis') }} as k
    inner join variants as v
        on
            k.product = v.product
            and k.reported_as = v.reported_as
    left join {{ ref('metric_net_revenue') }} as c
        on
            k.period_month = c.period_month
            and k.product = c.product

),

measured as (

    select
        *,
        reported_value - canonical_value as diff,
        100.0 * (reported_value - canonical_value) / nullif(canonical_value, 0) as diff_pct
    from joined

)

select
    period_month,
    product,
    reported_as,
    {{ to_numeric('reported_value') }} as reported_value,
    {{ to_numeric('canonical_value') }} as canonical_value,
    {{ to_numeric('diff') }} as diff,
    {{ to_numeric('diff_pct') }} as diff_pct,
    expected_direction,
    {{ to_numeric('threshold_pct') }} as threshold_pct,
    comparable,
    case
        when not comparable then null
        when diff_pct is null then false
        else
            abs(diff_pct) <= threshold_pct
            and case expected_direction
                when 'higher' then diff_pct >= -direction_tolerance_pct
                when 'lower' then diff_pct <= direction_tolerance_pct
                else true
            end
    end as explained
from measured
