-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    account_key,
    company_name,
    {{ mask_initial('contact_name') }} as contact_name_initial,
    {{ mask_initial('sales_owner') }} as sales_owner_initial,
    seats,
    monthly_fee_yen,
    first_month,
    last_month,
    status,
    is_active
from {{ ref('dim_account') }}
