-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    product,
    {{ pseudonym('household_key', 'D') }} as household_key,
    n_members,
    is_family,
    first_seen_at
from {{ ref('dim_household_by_product') }}
where product = 'D'
