-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    contract_id,
    generation,
    member_id,
    {{ pseudonym('member_key', 'C') }} as member_key,
    plan_ref,
    plan_key,
    monthly_fee_tax_incl,
    monthly_fee_ex_tax,
    start_date,
    end_date,
    payer_member_id,
    status,
    valid_from,
    valid_to,
    is_current,
    is_deleted
from {{ ref('scd_contract') }}
