-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    plan_ref,
    source,
    generation,
    source_plan_code,
    plan_key,
    plan_name,
    billing_period_months
from {{ ref('dim_plan') }}
