-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    period_month,
    product,
    reported_as,
    reported_value,
    canonical_value,
    diff,
    diff_pct,
    expected_direction,
    threshold_pct,
    comparable,
    explained
from {{ ref('recon_active_members') }}
where product = 'D'
