-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    period_month,
    product,
    active_members
from {{ ref('metric_active_members') }}
where product = 'A'
