-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    product,
    {{ pseudonym('member_key', 'A') }} as member_key,
    source_member_id,
    {{ pseudonym('household_key', 'A') }} as household_key,
    key_method,
    {{ mask_initial('name') }} as name_initial,
    {{ mask_initial('name_kana') }} as name_kana_initial,
    {{ mask_email_domain('email') }} as email_domain,
    {{ mask_phone_last4('phone') }} as phone_last4,
    {{ mask_birth_year('birth_date') }} as birth_date_year,
    joined_at
from {{ ref('dim_member_by_product') }}
where product = 'A'
