-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    account_key,
    company_name,
    contact_name,
    sales_owner,
    seats,
    monthly_fee_yen,
    first_month,
    last_month,
    status,
    is_active
from {{ ref('dim_account') }}
