-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    member_key,
    household_key,
    key_method,
    {{ mask_initial('name') }} as name_initial,
    {{ mask_initial('name_kana') }} as name_kana_initial,
    {{ mask_email_domain('email') }} as email_domain,
    {{ mask_phone_last4('phone') }} as phone_last4,
    {{ mask_birth_year('birth_date') }} as birth_date_year,
    first_seen_at,
    in_a,
    in_b,
    in_c,
    in_d,
    n_products
from {{ ref('dim_member') }}
