-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    source,
    dataset,
    partition_date,
    files_landed,
    rows_landed,
    files_quarantined,
    violations
from {{ ref('ingest_quality_daily') }}
where source = 'C'
