-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    period_month,
    product,
    churned_members
from {{ ref('metric_churned_members') }}
where product = 'A'
