-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    session_id,
    source,
    session_type,
    {{ pseudonym('member_key', 'A') }} as member_key,
    started_at,
    session_date_jst,
    duration_min,
    facility_id
from {{ ref('fct_session') }}
where source = 'A'
