-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    period_month,
    product,
    sessions_per_active_member
from {{ ref('metric_sessions_per_active_member') }}
where product = 'B'
