-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
{{ config(tags=['audit']) }}

select
    event_id,
    occurred_at,
    outcome,
    principal,
    role,
    sql_hash,
    sql_normalized,
    referenced_tables,
    referenced_columns,
    sensitive_columns,
    touched_sensitive,
    row_count,
    deny_reason
from {{ ref('audit_access_log') }}
