-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    household_key,
    n_members,
    is_family,
    in_a,
    in_b,
    in_c,
    in_d,
    first_seen_at
from {{ ref('dim_household') }}
