-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    booking_id,
    tenant_id,
    {{ pseudonym('member_key', 'B') }} as member_key,
    booked_at,
    class_start_at,
    class_date_jst,
    status,
    price_ex_tax,
    price_tax_incl,
    tax_rate,
    is_deleted,
    as_of_snapshot
from {{ ref('fct_booking') }}
