-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    payment_id,
    source,
    payment_type,
    member_key,
    plan_ref,
    occurred_at,
    amount_ex_tax,
    amount_tax_incl,
    amount_original,
    amount_original_basis,
    tax_rate
from {{ ref('fct_payment') }}
where source = 'E'
