-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    member_key,
    household_key,
    key_method,
    name,
    name_kana,
    email,
    phone,
    birth_date,
    health_notes,
    medical_conditions,
    first_seen_at,
    in_a,
    in_b,
    in_c,
    in_d,
    n_products
from {{ ref('dim_member') }}
