-- GENERATED by `platform access generate` from policies/access.yml - do not edit.
select
    activity_id,
    member_key,
    occurred_at,
    activity_date_jst,
    activity_type,
    source
from {{ ref('fct_activity') }}
where source = 'C'
