"""Generate the gold metric models, reconciliation models and docs from the spec (F1).

The output is a ``{repo-relative path: file content}`` mapping so that ``generate`` (write) and
``check`` (compare) use exactly the same text. Every file starts with a "generated - do not
edit" header.
"""

from __future__ import annotations

from typing import Any, Final

from .spec import Metric, MetricsSpec, SpecError, Variant

HEADER: Final = "GENERATED by `platform metrics generate` from metrics/metrics.yml - do not edit."
METRICS_DIR: Final = "dbt/models/gold/metrics"
RECON_DIR: Final = "dbt/models/gold/recon"
DOCS_PATH: Final = "docs/metrics.md"
NUMERIC: Final = "numeric(28,6)"
_CONFIG: Final = (
    "    config:\n      contract:\n        enforced: true\n      meta:\n        generated: true\n"
)


def _sql(text: str) -> str:
    return f"-- {HEADER}\n" + text.strip("\n") + "\n"


def _fill(template: str, **values: str) -> str:
    for key, value in values.items():
        template = template.replace(f"@{key}@", value)
    return template


def _active(spec: MetricsSpec, metric: Metric) -> Metric:
    if metric.kind in {"distinct_entities_in_window", "sum_by_month"}:
        return metric
    return spec.by_name(str(metric.definition["active_metric"]))


def _scoped_cte(spec: MetricsSpec, metric: Metric, active: Metric) -> str:
    scopes = spec.scopes_of(metric)
    parts: list[str] = []
    for product, scope in scopes.items():
        if scope == "all":
            parts.append(
                "    select\n        'ALL' as product,\n        entity,\n        event_date,\n"
                "        row_id\n    from filtered"
            )
        elif scope == "source":
            parts.append(
                f"    select\n        '{product}' as product,\n        entity,\n"
                f"        event_date,\n        row_id\n    from filtered\n"
                f"    where source = '{product}'"
            )
        else:
            parts.append(
                f"    select\n        '{product}' as product,\n        f.entity,\n"
                f"        f.event_date,\n        f.row_id\n    from filtered as f\n"
                f"    inner join {{{{ ref('dim_member_product') }}}} as p\n"
                f"        on f.entity = p.member_key\n    where p.product = '{product}'"
            )
    del active
    return "scoped as (\n\n" + "\n\n    union all\n\n".join(parts) + "\n\n)"


def _window_ctes(active: Metric) -> str:
    d = active.definition
    model, filt = d["model"], d["filter"]
    return _fill(
        """
months as (

    select distinct
        {{ month_start('@DATE@') }} as period_month,
        {{ month_end_date('@DATE@') }} as month_end
    from {{ ref('@MODEL@') }}

),

filtered as (

    select
        @ENTITY@ as entity,
        @DATE@ as event_date,
        @ROW@ as row_id,
        @SOURCE@
    from {{ ref('@MODEL@') }}
    where @FILTER@

)""",
        MODEL=model,
        DATE=d["date_column"],
        ENTITY=d["entity_column"],
        ROW=d["row_id_column"],
        SOURCE=("source" if d["source_column"] == "source" else f"{d['source_column']} as source"),
        FILTER=filt,
    ).strip("\n")


def _window_join(active: Metric, base: str = "    ") -> str:
    days = int(active.definition["window_days"])
    return (
        f"{base}inner join scoped as s\n"
        f"{base}    on\n"
        f"{base}        {{{{ add_days('m.month_end', -{days}) }}}} < s.event_date\n"
        f"{base}        and m.month_end >= s.event_date"
    )


def _metric_sql(spec: MetricsSpec, metric: Metric) -> str:
    active = _active(spec, metric)
    if metric.kind == "distinct_entities_in_window":
        body = (
            "with\n"
            + _window_ctes(metric)
            + ",\n\n"
            + _scoped_cte(spec, metric, metric)
            + f"\n\nselect\n    m.period_month,\n    s.product,\n"
            f"    count(distinct s.entity) as {metric.name}\n"
            f"from months as m\n{_window_join(metric, '')}\n"
            "group by m.period_month, s.product"
        )
    elif metric.kind == "sum_by_month":
        d = metric.definition
        scopes = spec.scopes_of(metric)
        if "population" in scopes.values():
            raise SpecError(f"{metric.name}: sum_by_month cannot use a population scope")
        parts = []
        for product, scope in scopes.items():
            label = "'ALL'" if scope == "all" else f"'{product}'"
            where = "" if scope == "all" else f"\n    where source = '{product}'"
            parts.append(
                f"    select\n        {label} as product,\n        period_month,\n"
                f"        amount\n    from dated{where}"
            )
        body = _fill(
            """
with dated as (

    select
        source,
        {{ month_start(to_date_jst('@TS@')) }} as period_month,
        @AMOUNT@ as amount
    from {{ ref('@MODEL@') }}

),

scoped as (

@PARTS@

)

select
    period_month,
    product,
    {{ to_bigint('sum(amount)') }} as @NAME@
from scoped
group by period_month, product""",
            TS=d["timestamp_column"],
            AMOUNT=d["amount_column"],
            MODEL=d["model"],
            PARTS="\n\n    union all\n\n".join(parts),
            NAME=metric.name,
        )
    elif metric.kind == "lapsed_between_windows":
        body = (
            "with\n"
            + _window_ctes(active)
            + ",\n\n"
            + _scoped_cte(spec, metric, active)
            + ",\n\nactive_sets as (\n\n    select distinct\n        m.period_month,\n"
            "        s.product,\n        s.entity\n    from months as m\n"
            + _window_join(active)
            + "\n\n)\n\n"
            + f"select\n    m.period_month,\n    prev.product,\n    count(*) as {metric.name}\n"
            "from months as m\ninner join active_sets as prev\n"
            "    on prev.period_month = {{ month_start(add_days('m.period_month', -1)) }}\n"
            "left join active_sets as cur\n"
            "    on\n"
            "        m.period_month = cur.period_month\n"
            "        and prev.product = cur.product\n"
            "        and prev.entity = cur.entity\n"
            "where cur.entity is null\n"
            "group by m.period_month, prev.product"
        )
    else:  # rows_per_active
        body = (
            "with\n"
            + _window_ctes(active)
            + ",\n\n"
            + _scoped_cte(spec, metric, active)
            + ",\n\nwindow_rows as (\n\n    select\n        m.period_month,\n"
            "        s.product,\n        count(*) as n_rows\n    from months as m\n"
            + _window_join(active)
            + "\n    group by m.period_month, s.product\n\n)\n\n"
            + f"select\n    w.period_month,\n    w.product,\n"
            f"    {{{{ to_numeric('1.0 * w.n_rows / nullif(a.{active.name}, 0)') }}}} "
            f"as {metric.name}\n"
            "from window_rows as w\n"
            f"inner join {{{{ ref('metric_{active.name}') }}}} as a\n"
            "    on\n"
            "        w.period_month = a.period_month\n"
            "        and w.product = a.product"
        )
    return _sql(body)


def _value_type(metric: Metric) -> str:
    return NUMERIC if metric.kind == "rows_per_active" else "int64"


def _yaml_str(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _column(name: str, data_type: str, description: str, tests: str = "") -> str:
    return (
        f"      - name: {name}\n        description: {_yaml_str(description)}\n"
        f"        data_type: {data_type}\n"
        f"        config:\n          meta:\n            pii: none\n{tests}"
    )


def metric_columns(metric: Metric) -> list[tuple[str, str]]:
    """``(column, data type)`` of a generated metric model."""
    return [("period_month", "date"), ("product", "string"), (metric.name, _value_type(metric))]


def metric_descriptions(metric: Metric) -> dict[str, str]:
    """Column descriptions of a generated metric model."""
    return {
        "period_month": "First day of the month the value is for.",
        "product": "Product code (A-D) the value is scoped to, or ALL for the whole platform.",
        metric.name: metric.description,
    }


RECON_DESCRIPTIONS: Final = {
    "period_month": "First day of the month.",
    "product": "Product that reports the KPI.",
    "reported_as": "The product's own name for the KPI.",
    "reported_value": "The value the product reports.",
    "canonical_value": "The canonical metric for the same product scope and month.",
    "diff": "Reported minus canonical.",
    "diff_pct": "Difference as a percentage of the canonical value.",
    "expected_direction": "Known relationship of the reported value to the canonical one.",
    "threshold_pct": "Largest absolute diff_pct that the known definition difference explains.",
    "comparable": "False when the canonical metric has no counterpart for this KPI.",
    "explained": "True when the gap is inside its known band; empty when not comparable.",
}


def _metric_yml(metric: Metric) -> str:
    nn = "        data_tests: [not_null]\n"
    described = metric_descriptions(metric)
    cols = "".join(_column(n, t, described[n], nn) for n, t in metric_columns(metric))
    return (
        f"# {HEADER}\nversion: 2\n\nmodels:\n  - name: metric_{metric.name}\n"
        f"    description: {_yaml_str(metric.description)}\n" + _CONFIG + f"    columns:\n{cols}"
        "    data_tests:\n      - dbt_utils.unique_combination_of_columns:\n"
        "          arguments:\n            combination_of_columns: [period_month, product]\n"
    )


def _num(value: float) -> str:
    return f"{value:.1f}"


def _variants_cte(variants: tuple[Variant, ...]) -> str:
    rows = []
    for v in variants:
        rows.append(
            f"    select\n        '{v.product}' as product,\n"
            f"        '{v.reported_as}' as reported_as,\n"
            f"        '{v.expected_direction}' as expected_direction,\n"
            f"        {_num(v.direction_tolerance_pct)} as direction_tolerance_pct,\n"
            f"        {_num(v.threshold_pct)} as threshold_pct,\n"
            f"        {'true' if v.comparable else 'false'} as comparable"
        )
    return "\n\n    union all\n\n".join(rows)


def _recon_sql(metric: Metric) -> str:
    name = metric.name
    return _sql(
        _fill(
            """
with variants as (

@VARIANTS@

),

joined as (

    select
        k.period_month,
        k.product,
        k.reported_as,
        k.value as reported_value,
        c.@NAME@ as canonical_value,
        v.expected_direction,
        v.direction_tolerance_pct,
        v.threshold_pct,
        v.comparable
    from {{ ref('brz_reported_kpis') }} as k
    inner join variants as v
        on
            k.product = v.product
            and k.reported_as = v.reported_as
    left join {{ ref('metric_@NAME@') }} as c
        on
            k.period_month = c.period_month
            and k.product = c.product

),

measured as (

    select
        *,
        reported_value - canonical_value as diff,
        100.0 * (reported_value - canonical_value) / nullif(canonical_value, 0) as diff_pct
    from joined

)

select
    period_month,
    product,
    reported_as,
    {{ to_numeric('reported_value') }} as reported_value,
    {{ to_numeric('canonical_value') }} as canonical_value,
    {{ to_numeric('diff') }} as diff,
    {{ to_numeric('diff_pct') }} as diff_pct,
    expected_direction,
    {{ to_numeric('threshold_pct') }} as threshold_pct,
    comparable,
    case
        when not comparable then null
        when diff_pct is null then false
        else
            abs(diff_pct) <= threshold_pct
            and case expected_direction
                when 'higher' then diff_pct >= -direction_tolerance_pct
                when 'lower' then diff_pct <= direction_tolerance_pct
                else true
            end
    end as explained
from measured""",
            NAME=name,
            VARIANTS=_variants_cte(metric.known_variants),
        )
    )


RECON_COLUMNS: Final = (
    ("period_month", "date"),
    ("product", "string"),
    ("reported_as", "string"),
    ("reported_value", NUMERIC),
    ("canonical_value", NUMERIC),
    ("diff", NUMERIC),
    ("diff_pct", NUMERIC),
    ("expected_direction", "string"),
    ("threshold_pct", NUMERIC),
    ("comparable", "boolean"),
    ("explained", "boolean"),
)


def _unit_tests(metric: Metric) -> str:
    variant = next((v for v in metric.known_variants if v.comparable), None)
    if variant is None:
        return ""
    base = 1000.0
    sign = -1.0 if variant.expected_direction == "lower" else 1.0
    within = base * (1 + sign * variant.threshold_pct / 200)
    over = base * (1 + sign * variant.threshold_pct * 2 / 100)
    cases: list[tuple[str, float, str]] = [
        ("within_threshold_and_direction_is_explained", within, "true"),
        ("beyond_the_threshold_is_not_explained", over, "false"),
    ]
    if variant.expected_direction != "any":
        wrong = base * (
            1 - sign * (variant.direction_tolerance_pct + variant.threshold_pct / 2) / 100
        )
        cases.append(("wrong_direction_is_not_explained", wrong, "false"))
    out = "\nunit_tests:\n"
    for label, value, explained in cases:
        out += (
            f"  - name: recon_{metric.name}_{label}\n"
            f"    model: recon_{metric.name}\n"
            "    given:\n"
            "      - input: ref('brz_reported_kpis')\n"
            "        rows:\n"
            f"          - {{product: {variant.product}, reported_as: {variant.reported_as}, "
            f'period_month: "2026-01-01", value: {value:.1f}}}\n'
            f"      - input: ref('metric_{metric.name}')\n"
            "        rows:\n"
            f'          - {{period_month: "2026-01-01", product: {variant.product}, '
            f"{metric.name}: {base:.1f}}}\n"
            "    expect:\n"
            "      rows:\n"
            f"        - {{reported_as: {variant.reported_as}, comparable: true, "
            f"explained: {explained}}}\n"
        )
    return out


def _recon_description(metric: Metric) -> str:
    return f"Each product KPI of `{metric.name}` against the canonical value."


def _recon_yml(metric: Metric) -> str:
    cols = "".join(_column(n, t, RECON_DESCRIPTIONS[n]) for n, t in RECON_COLUMNS)
    return (
        f"# {HEADER}\nversion: 2\n\nmodels:\n  - name: recon_{metric.name}\n"
        f"    description: {_yaml_str(_recon_description(metric))}\n"
        + _CONFIG
        + f"    columns:\n{cols}"
        "    data_tests:\n      # A comparable variant must be explained by its known_variant\n"
        "      # (direction and threshold in metrics.yml); anything else fails here.\n"
        "      - dbt_utils.expression_is_true:\n"
        "          arguments:\n            expression: coalesce(explained, true)\n"
        + _unit_tests(metric)
    )


def _docs(spec: MetricsSpec) -> str:
    lines = [
        f"<!-- {HEADER} -->",
        "",
        "# Metrics",
        "",
        "Canonical definitions of the shared metrics and the differently defined KPIs the",
        "products report under similar names. Source: `metrics/metrics.yml`.",
        "",
    ]
    for m in spec.metrics:
        active = _active(spec, m)
        lines += [
            f"## {m.name}",
            "",
            m.description,
            "",
            f"* kind: `{m.kind}`, grain: {', '.join(m.grain)}, owner: {m.owner}",
            f"* model: `metric_{m.name}`, reconciliation: `recon_{m.name}`",
        ]
        if m.kind == "distinct_entities_in_window":
            d = m.definition
            lines.append(
                f"* counts distinct `{d['entity_column']}` of `{d['model']}` where "
                f"`{d['filter']}` within {d['window_days']} days"
            )
        elif m.kind != "sum_by_month":
            lines.append(f"* derived from `{active.name}`")
        lines += [
            "",
            "| product | reported as | comparable | expected | threshold % | "
            "how the product defines it |",
            "|---|---|---|---|---|---|",
        ]
        for v in m.known_variants:
            expected = v.expected_direction if v.comparable else "n/a"
            thr = _num(v.threshold_pct) if v.comparable else "n/a"
            text = v.definition + ("" if v.comparable else f" (not comparable: {v.note})")
            lines.append(
                f"| {v.product} | `{v.reported_as}` | {'yes' if v.comparable else 'no'} | "
                f"{expected} | {thr} | {text} |"
            )
        lines.append("")
    return "\n".join(lines)


def generate_files(spec: MetricsSpec) -> dict[str, str]:
    """Every generated file as ``{repo-relative path: content}``."""
    files: dict[str, str] = {}
    for metric in spec.metrics:
        files[f"{METRICS_DIR}/metric_{metric.name}.sql"] = _metric_sql(spec, metric)
        files[f"{METRICS_DIR}/metric_{metric.name}.yml"] = _metric_yml(metric)
        files[f"{RECON_DIR}/recon_{metric.name}.sql"] = _recon_sql(metric)
        files[f"{RECON_DIR}/recon_{metric.name}.yml"] = _recon_yml(metric)
    files[DOCS_PATH] = _docs(spec)
    return files


def generated_descriptions(spec: MetricsSpec) -> dict[str, dict[str, str]]:
    """Column descriptions of every generated model (used by the access layer)."""
    out: dict[str, dict[str, str]] = {}
    for metric in spec.metrics:
        out[f"metric_{metric.name}"] = metric_descriptions(metric)
        out[f"recon_{metric.name}"] = dict(RECON_DESCRIPTIONS)
    return out


def generated_columns(spec: MetricsSpec) -> dict[str, list[tuple[str, str]]]:
    """Columns (name, data type) of every generated model (used by the access layer)."""
    out: dict[str, list[tuple[str, str]]] = {}
    for metric in spec.metrics:
        out[f"metric_{metric.name}"] = metric_columns(metric)
        out[f"recon_{metric.name}"] = list(RECON_COLUMNS)
    return out


def describe(spec: MetricsSpec) -> list[dict[str, Any]]:
    """A small summary used by the CLI."""
    return [{"metric": m.name, "variants": len(m.known_variants)} for m in spec.metrics]
