-- GENERATED by `platform metrics generate` from metrics/metrics.yml - do not edit.
with
months as (

    select distinct
        {{ month_start('activity_date_jst') }} as period_month,
        {{ month_end_date('activity_date_jst') }} as month_end
    from {{ ref('fct_activity') }}

),

filtered as (

    select
        member_key as entity,
        activity_date_jst as event_date,
        activity_id as row_id,
        source
    from {{ ref('fct_activity') }}
    where activity_type in ('workout', 'visit', 'booking_attended')

),

scoped as (

    select
        'ALL' as product,
        entity,
        event_date,
        row_id
    from filtered

    union all

    select
        'A' as product,
        entity,
        event_date,
        row_id
    from filtered
    where source = 'A'

    union all

    select
        'B' as product,
        entity,
        event_date,
        row_id
    from filtered
    where source = 'B'

    union all

    select
        'C' as product,
        entity,
        event_date,
        row_id
    from filtered
    where source = 'C'

    union all

    select
        'D' as product,
        f.entity,
        f.event_date,
        f.row_id
    from filtered as f
    inner join {{ ref('dim_member_product') }} as p
        on f.entity = p.member_key
    where p.product = 'D'

),

active_sets as (

    select distinct
        m.period_month,
        s.product,
        s.entity
    from months as m
    inner join scoped as s
        on
            {{ add_days('m.month_end', -30) }} < s.event_date
            and m.month_end >= s.event_date

)

select
    m.period_month,
    prev.product,
    count(*) as churned_members
from months as m
inner join active_sets as prev
    on prev.period_month = {{ month_start(add_days('m.period_month', -1)) }}
left join active_sets as cur
    on
        m.period_month = cur.period_month
        and prev.product = cur.product
        and prev.entity = cur.entity
where cur.entity is null
group by m.period_month, prev.product
