-- GENERATED by `platform metrics generate` from metrics/metrics.yml - do not edit.
with dated as (

    select
        source,
        {{ month_start(to_date_jst('occurred_at')) }} as period_month,
        amount_tax_incl as amount
    from {{ ref('fct_payment') }}

),

scoped as (

    select
        'ALL' as product,
        period_month,
        amount
    from dated

    union all

    select
        'A' as product,
        period_month,
        amount
    from dated
    where source = 'A'

    union all

    select
        'D' as product,
        period_month,
        amount
    from dated
    where source = 'D'

)

select
    period_month,
    product,
    {{ to_bigint('sum(amount)') }} as net_revenue
from scoped
group by period_month, product
