-- GENERATED by `platform metrics generate` from metrics/metrics.yml - do not edit.
with
months as (

    select
        period_month,
        month_end
    from {{ ref('dim_month') }}

),

filtered as (

    select
        member_key as entity,
        activity_date_jst as event_date,
        activity_id as row_id,
        source
    from {{ ref('fct_activity') }}
    where activity_type in ('workout', 'visit', 'booking_attended')

),

scoped as (

    select
        'ALL' as product,
        entity,
        event_date,
        row_id
    from filtered

    union all

    select
        'A' as product,
        entity,
        event_date,
        row_id
    from filtered
    where source = 'A'

    union all

    select
        'B' as product,
        entity,
        event_date,
        row_id
    from filtered
    where source = 'B'

    union all

    select
        'C' as product,
        entity,
        event_date,
        row_id
    from filtered
    where source = 'C'

    union all

    select
        'D' as product,
        f.entity,
        f.event_date,
        f.row_id
    from filtered as f
    inner join {{ ref('dim_member_product') }} as p
        on f.entity = p.member_key
    where p.product = 'D'

),

counted as (

    select
        m.period_month,
        s.product,
        count(distinct s.entity) as n
    from months as m
    inner join scoped as s
        on
            {{ add_days('m.month_end', -30) }} < s.event_date
            and m.month_end >= s.event_date
    group by m.period_month, s.product

),

products as (

    select 'ALL' as product

    union all

    select 'A' as product

    union all

    select 'B' as product

    union all

    select 'C' as product

    union all

    select 'D' as product

)

select
    m.period_month,
    p.product,
    coalesce(c.n, 0) as active_members
from months as m
cross join products as p
left join counted as c
    on
        m.period_month = c.period_month
        and p.product = c.product
