-- GENERATED by `platform metrics generate` from metrics/metrics.yml - do not edit.
with months as (

    select period_month
    from {{ ref('dim_month') }}

),

dated as (

    select
        source,
        {{ month_start(to_date_jst('occurred_at')) }} as period_month,
        amount_tax_incl as amount
    from {{ ref('fct_payment') }}

),

scoped as (

    select
        'ALL' as product,
        period_month,
        amount
    from dated

    union all

    select
        'A' as product,
        period_month,
        amount
    from dated
    where source = 'A'

    union all

    select
        'D' as product,
        period_month,
        amount
    from dated
    where source = 'D'

),

counted as (

    select
        period_month,
        product,
        {{ to_bigint('sum(amount)') }} as total
    from scoped
    group by period_month, product

),

products as (

    select 'ALL' as product

    union all

    select 'A' as product

    union all

    select 'D' as product

)

select
    m.period_month,
    p.product,
    coalesce(c.total, 0) as net_revenue
from months as m
cross join products as p
left join counted as c
    on
        m.period_month = c.period_month
        and p.product = c.product
